/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.khuyenmai;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.KhuyenmaiService;

/**
 *
 * @author NGUYEN DINH BACH
 */
public class formkhuyenmai extends javax.swing.JPanel {

    private KhuyenmaiService kms = new KhuyenmaiService();
    private DefaultTableModel model = new DefaultTableModel();
    private int a = -1;
    public static boolean isNumeric(String str) {
    return str.matches("-?\\d+(\\.\\d+)?");}
    public formkhuyenmai() {
        initComponents();
        this.fillTable(kms.getAll());
    }
        void fillTable(ArrayList<khuyenmai> list) {
        model = (DefaultTableModel) tblbangkhuyenmai.getModel();
        model.setRowCount(0);
        for (khuyenmai kmm : list) {
            model.addRow(kmm.toDatarow());
        }
    }
        khuyenmai readForm() {
        String ngaybd,ngaykt,tenkm;
        int giatri;
        boolean trangthai;
            
        
         tenkm = txttenkm.getText().trim();
        if (tenkm.isEmpty()) {//mã rỗng
            JOptionPane.showMessageDialog(this, "chưa nhập họ tên km ");
            txttenkm.requestFocus();//chuyển chuột về test mã
            return null;//dừng chương trình

        }
         
        
        
        ngaybd = txtNgaybatdau.getText().trim();
        if (ngaybd.isEmpty()) {//mã rỗng
            JOptionPane.showMessageDialog(this, "chưa nhập họ ngày bắt đầu");
            txtNgaybatdau.requestFocus();//chuyển chuột về test mã
            return null;//dừng chương trình

        }
        
        ngaykt = txtNgayketthuc.getText().trim();
        if (ngaykt.isEmpty()) {//mã rỗng
            JOptionPane.showMessageDialog(this, "chưa nhập họ ngày kết thúc");
            txtNgayketthuc.requestFocus();//chuyển chuột về test mã
            return null;//dừng chương trình

        }
        
        if (txtgiatri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa nhập giá trị km");
            txtgiatri.requestFocus();
            return null;
        }
        String inputMakm = txtgiatri.getText().trim();
        if (!isNumeric(inputMakm)) {
            JOptionPane.showMessageDialog(this, "giá trị km phải là số");
            txtgiatri.requestFocus();//chuyển chuột về test mã
            return null;//dừng chương trình

        }try {
            giatri = Integer.parseInt(inputMakm);
            if (giatri <= 0) {
                JOptionPane.showMessageDialog(this, "giá trị km phải lớn hơn 0");
                txtgiatri.setText("");
                txtgiatri.requestFocus();
                return null;
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "giá trị phải là số");
            txtgiatri.requestFocus();
            return null;
        }
         // Kiểm tra trạng thái từ combobox
    String selectedTrangThai = (String) cbbtrangthai.getSelectedItem();
    if (selectedTrangThai == null || selectedTrangThai.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái");
        cbbtrangthai.requestFocus();
        return null;
    }
    // Xác định trạng thái dựa vào giá trị của combobox
    trangthai = selectedTrangThai.equals("Đang hoạt động");
    
    // Trả về một mảng các đối tượng chứa dữ liệu

    
         return new khuyenmai(giatri, tenkm, ngaybd, ngaykt, trangthai);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbangkhuyenmai = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmakm = new javax.swing.JTextField();
        txttimkiembangkhuyenmai = new javax.swing.JTextField();
        txttenkm = new javax.swing.JTextField();
        txtgiatri = new javax.swing.JTextField();
        txtNgaybatdau = new javax.swing.JTextField();
        txtNgayketthuc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbbtrangthai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bảng Khuyến Mãi"));

        tblbangkhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Tên Khuyến Mãi", "Ngày bắt đầu", "Ngày kết thúc", "Giá trị", "Trạng thái"
            }
        ));
        tblbangkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangkhuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbangkhuyenmai);

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày Bắt Đầu");

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jLabel7.setText("Ngày kết thúc");

        jLabel8.setText("Tìm Kiếm");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Quản Lí Khuyến Mãi");

        cbbtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Kết thúc" }));
        cbbtrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbtrangthaiActionPerformed(evt);
            }
        });

        jLabel2.setText("MãKH");

        jLabel3.setText("TênKH");

        jLabel4.setText("Giá trị");

        jLabel5.setText("Trạng thái");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimkiembangkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txttenkm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmakm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtgiatri, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(btnadd))
                            .addComponent(jLabel5)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnedit))
                    .addComponent(cbbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmakm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttenkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtgiatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNgaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNgayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit)
                    .addComponent(btndelete)
                    .addComponent(btnadd))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiembangkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbtrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbtrangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbtrangthaiActionPerformed

    private void tblbangkhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangkhuyenmaiMouseClicked
        // TODO add your handling code here:
       a = tblbangkhuyenmai.getSelectedRow();
        String trangthai;
        txtmakm.setText(tblbangkhuyenmai.getValueAt(a, 0).toString());
        txttenkm.setText(tblbangkhuyenmai.getValueAt(a, 1).toString());
        txtNgaybatdau.setText(tblbangkhuyenmai.getValueAt(a, 2).toString());
        txtNgayketthuc.setText(tblbangkhuyenmai.getValueAt(a, 3).toString());
        txtgiatri.setText(tblbangkhuyenmai.getValueAt(a, 4).toString());
        trangthai = tblbangkhuyenmai.getValueAt(a, 5).toString();
         if (trangthai.equals("đang hoạt động")) {
        cbbtrangthai.setSelectedItem("Đang hoạt động");
    } else {
        cbbtrangthai.setSelectedItem("Kết thúc");
    }
     
    }//GEN-LAST:event_tblbangkhuyenmaiMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if(this.readForm()!= null){//thêm được
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có thêm không?");
            if(chon == 0){//có thêm
                kms.them(this.readForm()); // thêm vào database
                this.fillTable(kms.getAll());
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không chọn thêm");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
             
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
          if(this.readForm()!= null){//xóa được
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa không?");
            if(chon == 0){//có thêm
                kms.xoa(this.readForm());  
                model.removeRow(a);
                JOptionPane.showMessageDialog(this, "Xóa thành công");      
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không chọn xóa");
            }
            }else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
          a = tblbangkhuyenmai.getSelectedRow();
        if (a >= 0) {
            khuyenmai km = readForm();
            if (km != null) {
                int manv = Integer.parseInt(tblbangkhuyenmai.getValueAt(a, 0).toString());
                if (kms.sua(manv, km) > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    fillTable(kms.getAll()); // Làm mới bảng
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để sửa.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btneditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JComboBox<String> cbbtrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbangkhuyenmai;
    private javax.swing.JTextField txtNgaybatdau;
    private javax.swing.JTextField txtNgayketthuc;
    private javax.swing.JTextField txtgiatri;
    private javax.swing.JTextField txtmakm;
    private javax.swing.JTextField txttenkm;
    private javax.swing.JTextField txttimkiembangkhuyenmai;
    // End of variables declaration//GEN-END:variables
}
